grafana:
  adminPassword: admin123

  ingress:
    enabled: true
    ingressClassName: nginx

    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod

    hosts:
      - grafana.pramod-leveling.space

    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.pramod-leveling.space

prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx

    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod

    hosts:
      - prometheus.pramod-leveling.space

    tls:
      - secretName: prometheus-tls
        hosts:
          - prometheus.pramod-leveling.space

  prometheusSpec:
    retention: 15d

alertmanager:
  ingress:
    enabled: true
    ingressClassName: nginx

    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod

    hosts:
      - alertmanager.pramod-leveling.space

    tls:
      - secretName: alertmanager-tls
        hosts:
          - alertmanager.pramod-leveling.space

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

additionalPrometheusRulesMap:
  cloudcart-alerts:
    groups:
      - name: cloudcart.rules

        rules:
          - alert: HighCPUUsage

            expr: |
              (
                sum(rate(container_cpu_usage_seconds_total{namespace="cloudcart-dev"}[5m]))
                /
                sum(kube_pod_container_resource_requests{namespace="cloudcart-dev",resource="cpu"})
              ) * 100 > 80

            for: 5m

            labels:
              severity: warning

            annotations:
              summary: "High CPU Usage"
              description: "CPU utilization exceeded 80% for 5 minutes."

          - alert: HighMemoryUsage

            expr: |
              (
                sum(container_memory_working_set_bytes{namespace="cloudcart-dev"})
                /
                sum(kube_pod_container_resource_requests{namespace="cloudcart-dev",resource="memory"})
              ) * 100 > 80

            for: 5m

            labels:
              severity: warning

            annotations:
              summary: "High Memory Usage"
              description: "Memory utilization exceeded 80% for 5 minutes."

          - alert: PodRestarting

            expr: |
              increase(
                kube_pod_container_status_restarts_total{
                  namespace="cloudcart-dev"
                }[10m]
              ) > 3

            for: 1m

            labels:
              severity: critical

            annotations:
              summary: "Pod Restarting Frequently"
              description: "A pod restarted more than 3 times in 10 minutes."

          - alert: HPAMaxReplicasReached

            expr: |
              kube_horizontalpodautoscaler_status_current_replicas
              ==
              kube_horizontalpodautoscaler_spec_max_replicas

            for: 2m

            labels:
              severity: warning

            annotations:
              summary: "HPA reached maximum replicas"
              description: "An HPA has reached its configured maximum replicas."
