apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-secret-store.yaml
  - postgres-external-secret.yaml
  - user-service-external-secret.yaml
  - order-service-external-secret.yaml
