apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: user-service-external-secret
  namespace: cloudcart-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: user-service-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: cloudcart/user-service
