apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: logging
  namespace: argocd

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: logging

  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki-stack
      targetRevision: 2.10.2

      helm:
        valueFiles:
          - $values/apps/logging/values.yaml

    - repoURL: https://github.com/Roshan0102/online-boutique-gitops.git
      targetRevision: main
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
