loki:
  enabled: true

  persistence:
    enabled: true
    storageClassName: gp2
    size: 20Gi

  config:
    auth_enabled: false

promtail:
  enabled: true

  config:
    clients:
      - url: http://logging-loki:3100/loki/api/v1/push

grafana:
  enabled: false
