apiVersion: v1
kind: ConfigMap

metadata:
  name: product-service-config
  namespace: cloudcart-dev

data:
  PORT: "5002"

  DB_HOST: "postgres"

  DB_PORT: "5432"

  DB_USER: "postgres"

  DB_NAME: "cloudcart_products"