apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres/postgres-secret.yaml
  - postgres/postgres-pvc.yaml
  - postgres/postgres-configmap.yaml
  - postgres/postgres-deployment.yaml
  - postgres/postgres-service.yaml
  - user-service/user-service-secret.yaml
  - user-service/user-service-configmap.yaml
  - user-service/user-service-deployment.yaml
  - user-service/user-service-service.yaml
