apiVersion: v1
kind: ConfigMap

metadata:
  name: order-service-config
  namespace: cloudcart-dev

data:
  PORT: "5003"

  DB_HOST: "postgres"

  DB_PORT: "5432"

  DB_USER: "postgres"

  DB_NAME: "cloudcart_orders"

  PRODUCT_SERVICE_URL: "http://product-service:5002"
